### ISSUE TITLE
Getting raw gyroscope data?

### ISSUE THREAD

**Issue by radames** [TangibleDisplay/twiz#14]
Is it possible to get the raw gyroscope from the board?

**Comment by honnet** [comment]
Yes, you can change the firmware: for example, instead of using yaw, pitch and roll, you can use gx, gy and gx in this function:
https://github.com/TangibleDisplay/twiz-fw/blob/master/src/imu.c#L134
(you might have to format the data, I don't remember the details)

**Comment by radames** [comment]
cool, do you know any guide for firmware update for that device? Is it using a bootloader that enables wireless update?

**Comment by honnet** [comment]
Yeah, @jocelynmass made an excellent guide here:
https://diyiot.wordpress.com
https://github.com/jocelynmass/nrf51

Nordic has wireless bootloader examples here:
https://github.com/NordicSemiconductor/?query=dfu

And I just got this programmer, you might like it:
http://www.aliexpress.com/item/STM32-Debugger-Emulator-Programmer-JLink-OB-ARM-Downloader-Instead-v8-SWD/32602444933.html

**Comment by radames** [comment]
ok, perfect, thanks!
